name: Build and Release (Debug)

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write # Required for reading/writing releases

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
